-- WhatsApp identity is no longer the phone number.
--
-- Meta issues every user a business-scoped user ID (BSUID, e.g.
-- "MX.1035735295580653") and, once a user adopts a @username, STOPS sending
-- their phone number in the webhook. A message with no phone number is simply
-- lost by an integration that keys on one — Meta does not replay it.
--
-- Everything downstream here is keyed by phone: wa_mensajes.numero,
-- conversaciones.numero, wa_pedidos.numero, cotizaciones.notas, and
-- detectarCliente's last-10-digits match. Rekeying all of that would be a
-- large, risky change, so identity is resolved at the edge instead: this table
-- maps whatever identifiers a message carries onto ONE immutable key, and the
-- rest of the app keeps using that key exactly as it used the phone number.
--
-- The three identifiers age differently, which is the whole reason this table
-- exists:
--
--   contact_id  Kapso's contact UUID. Stable. Kapso already does the portfolio
--               scoping and the BSUID-change merge on its side, so this is the
--               identifier that survives everything.
--   bsuid       Regenerated by Meta when the user changes phone number.
--   telefono    Disappears when the user adopts a username; changes on carrier
--               switch. An address, not an identity.
--
-- Single business portfolio per database (one connected number per deploy, and
-- Fiable/Ruli are separate InsForge projects), so a bare unique index on bsuid
-- is correct here. Two portfolios sharing one database would need
-- (portfolio, bsuid) — and would silently stitch two people together without
-- it.
CREATE TABLE public.wa_identidades (
  clave      TEXT PRIMARY KEY,   -- immutable downstream key; NEVER rewritten
  contact_id TEXT UNIQUE,        -- Kapso contact UUID
  bsuid      TEXT UNIQUE,        -- "MX." + up to 128 chars, or "MX.ENT." parent
  telefono   TEXT,               -- last phone seen, if we ever saw one
  username   TEXT,               -- "@name", only once they adopt one
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX wa_identidades_telefono_idx
  ON public.wa_identidades (telefono) WHERE telefono IS NOT NULL;

-- Same posture as wa_mensajes/wa_pedidos: the webhook writes via the admin
-- client, staff may read.
ALTER TABLE public.wa_identidades ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated read wa_identidades"
  ON public.wa_identidades FOR SELECT TO authenticated
  USING (public.requesting_user_id() IS NOT NULL);

GRANT SELECT ON public.wa_identidades TO authenticated;

-- Resolve one inbound message to its conversation key, recording whatever the
-- message taught us about the sender.
--
-- Match order is contact_id → bsuid → telefono, which is what turns a
-- regenerated BSUID into a MERGE instead of a second row: the customer changed
-- their phone number, Meta issued them a new BSUID, but Kapso's contact_id
-- still points at the same person. Matching phone-first would produce the
-- orphaned-history bug in both directions.
--
-- `clave` is assigned once and never rewritten. It is seeded from the phone
-- number so that every row already keyed by phone — wa_mensajes, conversaciones,
-- wa_pedidos, cotizaciones.notas — keeps matching without a data migration.
-- Someone first seen without a phone gets keyed by BSUID, which is fine
-- precisely because they have no history to preserve.
CREATE OR REPLACE FUNCTION public.wa_identidad_resolver(
  p_contact_id text DEFAULT NULL,
  p_bsuid      text DEFAULT NULL,
  p_telefono   text DEFAULT NULL,
  p_username   text DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_contact  text := nullif(btrim(coalesce(p_contact_id, '')), '');
  v_bsuid    text := nullif(btrim(coalesce(p_bsuid, '')), '');
  v_telefono text := nullif(btrim(coalesce(p_telefono, '')), '');
  v_username text := nullif(btrim(coalesce(p_username, '')), '');
  v_clave    text;
BEGIN
  -- Nothing to identify the sender by. The caller decides what to do; we will
  -- not invent a key.
  IF v_contact IS NULL AND v_bsuid IS NULL AND v_telefono IS NULL THEN
    RETURN NULL;
  END IF;

  -- Guard against a BSUID being passed in the phone slot (or vice versa) —
  -- that would write one person's identifier onto another's row, silently.
  IF v_telefono IS NOT NULL AND v_telefono ~ '^[A-Za-z]{2}\.' THEN
    RAISE EXCEPTION 'BSUID % llegó en el campo de teléfono', v_telefono;
  END IF;
  IF v_bsuid IS NOT NULL AND v_bsuid !~ '^[A-Za-z]{2}\.(ENT\.)?[A-Za-z0-9]{1,128}$' THEN
    RAISE EXCEPTION 'BSUID con formato inválido: %', v_bsuid;
  END IF;

  SELECT clave INTO v_clave FROM public.wa_identidades
   WHERE (v_contact  IS NOT NULL AND contact_id = v_contact)
   LIMIT 1;

  IF v_clave IS NULL THEN
    SELECT clave INTO v_clave FROM public.wa_identidades
     WHERE (v_bsuid IS NOT NULL AND bsuid = v_bsuid)
     LIMIT 1;
  END IF;

  IF v_clave IS NULL THEN
    SELECT clave INTO v_clave FROM public.wa_identidades
     WHERE (v_telefono IS NOT NULL AND telefono = v_telefono)
     LIMIT 1;
  END IF;

  IF v_clave IS NULL THEN
    -- First sight. Seed the key from the phone so existing phone-keyed history
    -- attaches to it; fall back to the BSUID, then the contact id.
    v_clave := coalesce(v_telefono, v_bsuid, v_contact);
    INSERT INTO public.wa_identidades (clave, contact_id, bsuid, telefono, username)
    VALUES (v_clave, v_contact, v_bsuid, v_telefono, v_username)
    ON CONFLICT (clave) DO NOTHING;
    RETURN v_clave;
  END IF;

  -- Known sender: refresh the volatile identifiers, never the key. coalesce
  -- keeps a phone we already learned when this message arrived without one.
  UPDATE public.wa_identidades
     SET contact_id = coalesce(v_contact,  contact_id),
         bsuid      = coalesce(v_bsuid,    bsuid),
         telefono   = coalesce(v_telefono, telefono),
         username   = coalesce(v_username, username),
         updated_at = NOW()
   WHERE clave = v_clave;

  RETURN v_clave;
END;
$$;
